- README.md
- frontend/css/style.css
- frontend/index.html
- frontend/scripts/script.js
Resolves #3 
---
Added initial folder structure for the project and linked necessary files (HTML, CSS, JS) for basic setup.
- Folder structure: Created backend, frontend, config, data, apache, and tests folders.
- File links: Linked CSS and JS files in index.html for basic setup.
- Apache setup: Added apache folder
> initial-commit

- frontend/css/style.css
- frontend/index.html
---
- added app div and base structure
- also added flexbox
- added files for routing (modularity)
> grundstruktur-aufbau

- frontend/css/home.css
- frontend/css/style.css
- frontend/index.html
- frontend/pages/home.js
- frontend/pages/list.js
- frontend/pages/meals.js
- frontend/pages/plan.js
- frontend/scripts/script.js
---
**Description:**
- Implemented basic routing functionality.
- Set up the initial structure for the `HomeTab`.
- Included dynamic loading of CSS based on the current route.
**Changes:**
- Added routing logic to handle page changes.
- Created `home.js` for `HomeTab` content.
- Added home.css
---
> Added Routing + HomeTab Basic Structure

- frontend/css/home.css
- frontend/css/style.css
- frontend/index.html
- frontend/pages/home.js
- frontend/scripts/script.js
---
- Implemented the base structure for HomeTab.
- Added input fields for calorie calculation (weight, height, age, gender, activity level).
- Integrated a dropdown menu for selecting options.
> added homeTab

- frontend/temp/home.html
- frontend/temp/list.html
- frontend/temp/meals.html
- frontend/temp/plan.html
> temp fixes

- frontend/css/list.css
- frontend/css/style.css
- frontend/index.html
- frontend/pages/list.js
- frontend/scripts/script.js
- frontend/temp/list.html
- Added base structure for list page
- Added button that generates list elements from a certain array
- Added features to list elements (checkbox)
- Added functionality of order button (alphabetic, food categories)
TODO: 
// function for getting the right food from data base still needs to be implemented!!
const array = ["Apfel", "Banane", "Tomate"]
List only gets expanded by these elements because the data base doesn't exist yet
> Expanded list page

- frontend/pages/home.js
- frontend/pages/list.js
- frontend/scripts/script.js
I changed all German comments into english comments
Lets also write comments in English from now on
> Changed comments to english

- frontend/pages/home.js
- frontend/pages/list.js
- frontend/scripts/script.js
> Revert "Changed comments to english"

- frontend/css/style.css
- frontend/index.html
was just temporarly for workflow
> was just temporarly for workflow

- data/data.sql
> SQL structure

- frontend/pages/meals.js
- frontend/scripts/script.js
frontend -> backend
backend -> frontend
> added communication

- frontend/pages/list.js
- I added an algorithm that regardless of the structure of the users input (for each ingredient) writes the input correctly into the list
- I also changed the instruction in the input field
> Created algorithm

- frontend/css/plan.css
- frontend/css/style.css
- frontend/index.html
- frontend/pages/plan.js
- frontend/temp/plan.html
-  statt routing haben wir ein array benutzt:
- with ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
TODO
> Grundstruktur plan tab

- frontend/pages/plan.js
Now dummy values appear if you change the weekday.
Resolves #72
> Added dummy values

- frontend/manifest.json
> changed to relative pfade

- frontend/css/style.css
- frontend/index.html
- frontend/manifest.json
> relative path + no zoom

- frontend/login.html
created login page:
- added dummy login for testing
- added eye to reveal password
- added google/apple API buttons (not implemented yet)
- added register tab
- added functionality to require the user to enter a valid email adress
todo:
> login page

- frontend/css/list.css
- frontend/pages/list.js
The inputof amount is now saved
Resolves #63
> Save input

- frontend/scripts/api.js
- frontend/scripts/js-pages/meals.js
- frontend/scripts/storage.js
connected apache reverse proxy with frontend
- added reverse proxy
- connected frontend with reverse proxy by: 
- using https and /api
- fetch('https://gfoh.ddns.net:6969/api/dishes') => in backend: /api/dishes
- also changed function and api endpoints in backend and in storage.js and apiBaseUrl in api.js
> connected apache reverse proxy with frontend

- frontend/index.html
- frontend/offline.html
- frontend/scripts/script.js
- sw copy 2.js
- sw copy.js
- sw.js
- Implements offline caching for PWA
- Adds network connectivity check with offline fallback
- Added service worker with precaching
- activated sw.js in /frontend/scripts/script.js
- Implemented online status check using a HEAD fetch request
- Updated fetch event to serve cached content or offline.html when offline
- Automatically deletes old caches on activate event
- Uses online-first caching strategy with cache fallback
1. First checks if there is an internet connection
2. Then try to fetch data from Server via Reverse Proxy -> Backend -> DB
3. Update cache
4. if offline use cache
5. if everything fails -> load offline.html
! => If too laggy, we could try a caching first approach!!!!
- changed header in index.html (übersichtlicher)
- added offline.html
> implemented service worker (offline functionality, caching)

- frontend/set-up/pages/account.html
- frontend/set-up/pages/log-in.html
- frontend/set-up/scripts/login.js
- frontend/set-up/scripts/register.js
- frontend/set-up/scripts/script-set-up.js
- frontend/set-up/style-sheets/general.css
- implemented Signup
- implemented Login
Made everything compatible with database
- implemented encryption for passwords 
- saving the hashed password in the database
- also saving the email & username in db
- implemented tokenization
- when logging in token is compared for session
> Register and login

- frontend/auth/admin.html
- frontend/auth/cook.html
- frontend/auth/cookTest.js
- frontend/auth/user.html
- frontend/html-pages/unauthorized.html
- frontend/index.html
- frontend/scripts/auth.js
- frontend/scripts/role-check/admin.js
- frontend/scripts/role-check/cook.js
- frontend/scripts/role-check/user.js
- Functionality to restrict page content based on permissions
- Functionality to read the user's role from the actual token and show or hide content accordingly
> role management implemented

- frontend/css/list.css
- frontend/html-pages/list.html
- frontend/scripts/js-pages/list.js
- added animation for active filter button
> filterbar-button-animation

- frontend/css/settings.css
- frontend/html-pages/settings.html
- frontend/scripts/js-pages/settings.js
- fixed bug - activity level disturbed goal
- now they have seperate classes!
> fixed bug - activity level disturbed goal

- backend/backend.js
- frontend/scripts/script.js
- frontend/scripts/storage.js
added API Endpoint to get dishes with ingredients
> added API Endpoint to get dishes with ingredients

- backend/backend.js
- frontend/scripts/api.js
- frontend/scripts/auth.js
- frontend/scripts/script.js
implemented:
- fetchDataWithToken() in api.js for get-requests with token in header
- checkSessionTokenValid() in auth.js for checking if token is valid/invalid => logout if invalid
- check every 5 min in script.js if session is still allowed
- currently set valid token time to 10 minutes for testing => later set it to a week or something like that
> session token auth

- frontend/css/home.css
- frontend/html-pages/home.html
- frontend/index.html
- frontend/scripts/script.js
- fixed routing + animation bugs
- when first loading we had the bug that routing didnt load initially and the animation was buggy. now works perfectly
> fixed routing + animation bugs

- frontend/css/home.css
- frontend/css/meals.css
- frontend/html-pages/list.html
- frontend/html-pages/meals.html
- frontend/scripts/js-pages/list.js
- frontend/scripts/js-pages/meals.js
- frontend/scripts/searchBar.js
- Implemented search bars in meals and list page
- Implemented filter bars in meals and list page
- blocked and preferred ingredients and meals are now displayed correctly in the corresponding container of the meals page
> Search and filter bars + preferred/blocked indicators

- frontend/css/home.css
- frontend/css/style.css
- frontend/html-pages/home.html
- frontend/html-pages/settings.html
- frontend/index.html
- frontend/scripts/js-pages/home.js
- frontend/scripts/js-pages/list.js
- frontend/scripts/js-pages/meals.js
- frontend/scripts/js-pages/plan.js
- frontend/scripts/js-pages/settings.js
- frontend/scripts/roleRouting.js
- frontend/scripts/script.js
- Routing for settings-page
- color bug fix for settings
- login: auf richtige seite weiterleioten
- settings cancel button auf richtige seite zurück (history)
> role-management-and-routing-for-settingspage

- frontend/html-pages/settings.html
- frontend/scripts/js-pages/settings.js
- frontend/scripts/script.js
- when closing the settings, you will get redirected to the last page where you have opened the settings from (history of lastHast is being remembered)
> close-settings-reference

- frontend/css/home.css
- frontend/html-pages/homeStandard.html
- frontend/scripts/roleRouting.js
- height media queries removed
- content isnt shrinkable anymore
> Fixed positioning of dashboard

- frontend/scripts/api.js
fetching bug when db is restarting:
- Problem was when DB was restarting and IN THIS MOMENT the user sends a post or get request => failed to fetch => no data
- so i fixed it by starting a new request after 1 second => only when 503 so if 404 happens it wont start again
> fetching bug when db is restarting

- frontend/css/home.css
- frontend/css/meals.css
- frontend/css/plan.css
- frontend/html-pages/meals.html
- frontend/html-pages/unauthorized.html
- frontend/scripts/js-pages/meals.js
- frontend/scripts/roleRouting.js
- frontend/scripts/storage.js
- frontend/scripts/swipetodelete.js
- frontend/set-up/pages/account.html
- After deleting one item you have to wait 500 milli sceonds before being able to delet a second item
- ckal are now rounded to integers
- You can only at one meal at a time (button.disabled property)
- The default category in meals overlay is now always displayed after opening
- Reset scrolling before displaying overlay
- Added better and consistent validation functions for overlays
- fixed unauthorized positioning (log in button)
- fixed account html text (log in to sign in)
- After cklicking on the ok btn of the alert window the overlays now wont close
> Bugs fixed (mostly preference page)

- frontend/scripts/js-pages/plan.js
- frontend/set-up/scripts/cardManager.js
- Calories are now calculated based on user data
> Calories calculation

- frontend/html-pages/settings.html
- frontend/scripts/algo/algo.js
- frontend/scripts/auth.js
- frontend/scripts/js-pages/plan.js
- frontend/scripts/js-pages/settings.js
- frontend/scripts/login.js
- frontend/scripts/script.js
- frontend/scripts/storage.js
- frontend/set-up/scripts/cardManager.js
- frontend/set-up/scripts/navigationManager.js
- frontend/set-up/scripts/pickerFactory.js
- Week Plan is synced with DB
- if there is a week plan in DB => load
- if not => create new one
- end of login pages => save LS data to DB + delete LS
- only load from DB (LS only to get some workaroud without routing)
- settings (load from db + save to db)
- load the right userData for the Algorithm !!!! 
---
+ EVERYTHING IS SYNCED WITH THE DB NOW 
+ YOU CAN USE THE APP FROM LOGIN TO CREATING A WEEK PLAN BASED ON YOUR DATA IN THE DATABASE 
+ YOU CAN CHANGE THE USER DATA IN THE SETTINGS
+ GENERATE A NEW PLAN BASED ON THE NEW DATA IN THE DB
> Storage Sync to DB

- frontend/scripts/js-pages/home.js
- frontend/scripts/storage.js
- fixed "cant change user role"
- and fixed "dont update usercount after deletion"
> fixed changing roles 

- frontend/set-up/pages/account.html
- frontend/set-up/pages/activity-level.html
- frontend/set-up/pages/age.html
- frontend/set-up/pages/gender.html
- frontend/set-up/pages/getstarted.html
- frontend/set-up/pages/goal.html
- frontend/set-up/pages/height.html
- frontend/set-up/pages/log-in.html
- frontend/set-up/pages/template.html
- frontend/set-up/pages/weight.html
- frontend/set-up/scripts/cardManager.js
- frontend/set-up/scripts/pickerFactory.js
- frontend/set-up/scripts/universalApplePicker.js
- frontend/set-up/style-sheets/general.css
- The already selected data is now displayed correclty after going back in set up pages
> Data saving issue fixed

- frontend/css/home.css
- frontend/css/settings.css
- frontend/css/style.css
- frontend/html-pages/homeStandard.html
- frontend/scripts/js-pages/home.js
- frontend/scripts/js-pages/settings.js
- frontend/scripts/script.js
- frontend/set-up/style-sheets/activity-level.css
Changes required in meals.js! Therefore merging...
- the next meals are now correctly displayed in the standard tab
- removed reset audio
- dark mode for user is implemented fully now
- the dark mode for the add overlays in meals.js has to be implemented 
- note: the new Item with the input fields to add an item now has an own class
> Several bug fixes

- frontend/css/list.css
- frontend/css/meals.css
- frontend/css/plan.css
- frontend/css/style.css
- frontend/html-pages/list.html
- frontend/html-pages/meals.html
- frontend/scripts/js-pages/home.js
- frontend/scripts/js-pages/list.js
- frontend/scripts/js-pages/meals.js
- frontend/scripts/js-pages/plan.js
- frontend/scripts/register.js
- frontend/set-up/pages/account.html
- frontend/set-up/pages/privacy-policy.html
- frontend/set-up/pages/terms-of-use.html
- frontend/set-up/scripts/AccountFormManager.js
- frontend/set-up/scripts/appInitializer.js
- frontend/set-up/style-sheets/account.css
- frontend/set-up/style-sheets/activity-level.css
- when going back the set up data now is saved
- you now have to accept the terms of use and the private policy to be able to register
- fixed the dark mode version for all overlays
- nav bar flash bug fixed
- added privacy policy and terms of use page
> Bug fixes v4

- frontend/scripts/algo/algo.js
- frontend/scripts/storage.js
user preferences are taken into account
- `chooseBestCandidate` will now take user preferences in account such as (in priority-order from highest to lowest):
- liked dishes
- liked ingredients
- neutral
- duplicates
- disliked ingredients
- disliked dishes
- added functionality to try to avoid using meal twice a day or more than twice a week! (will work even better if we have more data)
- added endpoint to get dishes WITH ingredient IDs AND support custom selection such as only category "main" or "breakfast" or "all" (default)
Here is the current Algo:
> user preferences are taken into account

- frontend/scripts/algo/algo.js
- frontend/scripts/js-pages/list.js
added-ingredientsArray-to-weekPlan
- added ingredients array for every dish => modified endpoint such as you dont only get the ingredientIDs but you get id, name, amount, unit
- also in algo I added another value amount_scaled which helps in weekPlan tab to get the cooking instructions instantly without another loop
- dont await 3 times => await Promise.all => send all requests parallel => big performance boost!
> added-ingredientsArray-to-weekPlan

- frontend/css/list.css
- frontend/html-pages/list.html
- frontend/scripts/js-pages/list.js
positioning-fixes-settings
- fixed settings positioning (scrolling) in list page
- improved responsive design when smaller screen and larger names
> positioning-fixes-list page

- frontend/css/drop-down.css
- frontend/css/meals.css
- frontend/css/settings.css
- frontend/css/style.css
- frontend/html-pages/meals.html
- frontend/html-pages/settings.html
- frontend/scripts/drop-down.js
- frontend/scripts/js-pages/home.js
- frontend/scripts/js-pages/meals.js
- frontend/scripts/js-pages/settings.js
- frontend/scripts/searchBar.js
- frontend/scripts/swipetodelete.js
- A horizontal and vertical swipe threshold must now be exceeded to prevent the user from accidentally swiping while scrolling
- Also when cklicking outside of the swiped element the swipe deletion is canceled.
- All dropdowns are now inetgrated into the settings page accordingly
- Added a callback function to the dropdown class to be able to add an eventListener and get Values while initializing the class
- Adapted drop down styles
- Added if statements to prevent non existing content from loading
- Fixed some dark mode styles (input fields in overlays)
> swipetodelete, dropdowns & home bug

- frontend/scripts/js-pages/home.js
- frontend/scripts/js-pages/list.js
- frontend/scripts/sound.js
Volume-module
- created Sound.js => play sound
- functionality to only play sound if its activated
- function for later to extend functionality to change Volume of sound globally
> Volume-module

- frontend/css/style.css
- frontend/set-up/style-sheets/general.css
more-native-select-disable
- removed user select + long press select etc. for more native app like feeling
> more-native-select-disable

- frontend/scripts/storage.js
- frontend/website/website.html
- added endpoint + storage module functions to support feedback-db sync
- also added the table columns name, email, etc. to expand it later for logged in users if needed
> feedback-db-support

- frontend/css/home.css
- frontend/css/list.css
- frontend/css/meals.css
- frontend/css/plan.css
- frontend/css/settings.css
- frontend/css/style.css
- frontend/html-pages/home.html
- frontend/html-pages/list.html
- frontend/html-pages/meals.html
- frontend/html-pages/plan.html
- frontend/html-pages/settings.html
- frontend/scripts/drop-down.js
- frontend/scripts/js-pages/home.js
- frontend/scripts/js-pages/list.js
- frontend/scripts/js-pages/meals.js
- frontend/scripts/js-pages/plan.js
- frontend/scripts/js-pages/settings.js
- frontend/scripts/native/native.js
- frontend/scripts/script.js
- node_modules/.vite/deps/_metadata.json
- Position of settings button ist now controlled by div headers of pages 
-> makes it easier to place it absolute if preferred + no problems with padding top of native app
-> needed this to make home completely scrollable
- padding top for native app should work now
- had to render it for every page container seperately because if you would have applied it to app container in the top there would be a white stripe when scrolling
BUT padding-bottom is applied to the app container otherwise the content at the bottom would have been cut off before nav bar starts (white stripe)
- the data that is written into the input field is now selected in the drop down menu
- added cursor pointer to all buttons
> Style improvements

- frontend/scripts/api.js
- frontend/scripts/native/nativeSw.js
- This is just a prototype of a second nativeSw.js which updates key:value in LS when fetching => in all cases get/post and also update from db every 60 seconds
- The idea is to make this one only for the native Apps (maybe with capacitor plugin) and for the PWA use the normal sw.js
=> doesnt work for all tabs, f.e. WeekPlan is laggy ??
> Native sw prototype
